### PR TITLE
chemical potentials added from eos

### PR DESCRIPTION
**Pull request by mari2895**
## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.
- [x] Make sure the copyright notice on any files you modified is up to date.
- [x] After creating a pull request, note it in the CHANGELOG.md file.
- [ ] LANL employees: make sure tests pass both on the github CI and on the Darwin CI

If preparing for a new release, in addition please check the following:
- [ ] Update the version in cmake.
- [ ] Move the changes in the CHANGELOG.md file under a new header for the new release, and reset the categories.

### CODE REVIEW

**Comment by mari2895** [comment]
> Pretty sure this should all work. Before merging, can you try calling it in phoebus to make sure it does what you expect?

I can, I am just not sure how to move on this particular fork from Phoebus externals.

**Comment by mari2895** [comment]
> Pretty sure this should all work. Before merging, can you try calling it in phoebus to make sure it does what you expect?

Checked and works correctly/returns reasonable values.

**Comment by Yurlungur** [comment]
:+1: will merge after tests pass

**Comment by mari2895** [comment]
> 👍 will merge after tests pass

sounds good! Thanks!

**Pull request merged**
