### PR TITLE
Fix SAP_Polynomial Fortran interface

### PR DESCRIPTION
**Pull request by jhp-lanl**
## PR Summary
Adds a missing C++ function to initialize the Fortran interface for the SAP_Polynomial EOS.

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Format your changes by using the `make format` command after configuring with `cmake`.
- N/A Document any new features, update documentation for changes made.
- [x] Make sure the copyright notice on any files you modified is up to date.
- N/A After creating a pull request, note it in the CHANGELOG.md file
- N/A If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Comment by jhp-lanl** [comment]
Any ideas why our CI didn't catch this either here or on gitlab? I'm happy to add any changes to make sure this is caught in the future.

**Review by Yurlungur — APPROVED** [review]
Do we have a fortran test binary that is called? Perhaps we should add one.

**Comment by jhp-lanl** [comment]
> Do we have a fortran test binary that is called? Perhaps we should add one.

I thought we did, but I'll make an issue

**Comment by gopsub** [comment]
Thanks for catching -- I should have RTFM-ed the "Contributing" section fully

**Comment by jhp-lanl** [comment]
> Thanks for catching -- I should have RTFM-ed the "Contributing" section fully

No worries @gopsub ! The fact that our testing doesn't cover this is a bigger issue than your omission IMO.

**Pull request merged**
