### PR TITLE
Add explicit dependency to sphinx-rtd-theme (and through it, jQuery)

### PR DESCRIPTION
**Pull request by rbberger**
## PR Summary

Newer Sphinx and sphinx-rtd-theme do not include jQuery, which is a necessary feature for `sphinx_multiversion` to properly work. This adds the `sphinx_rtd_theme` extension to our doc configuration, which also pulls in `sphinxcontrib-jquery` for us.

See 	https://blog.readthedocs.com/sphinx6-upgrade/

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.
- [x] Make sure the copyright notice on any files you modified is up to date.
- [x] After creating a pull request, note it in the CHANGELOG.md file
- [ ] If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Review by jhp-lanl — APPROVED** [review]
Thanks @rbberger for fixing this. I'll wait for @Yurlungur but I think this is a pretty straightforward change

Tagging @ktsai7 in case she has comments

**Review by Yurlungur — APPROVED** [review]
Thanks for the fix @rbberger !

**Comment by ktsai7** [comment]
just out of curiosity, since this is a fix, what was broken?

**Comment by rbberger** [comment]
@ktsai7  Newer versions of Sphinx and the rtd theme no longer include an embedded jQuery. Instead it now must be provided with the sphinxcontrib-jquery extension. rtd pulls that in for you, but for that you have to properly add it as extension to your config. Without jQuery, dynamic layout elements such as the version selection with multiversion fail due to missing JacaScript.

**Comment by Yurlungur** [comment]
I added the changelog and will merge when tests pass.

**Pull request merged**
