### PR TITLE
update cmakelists for release.

### PR DESCRIPTION
**Pull request by dholladay00**
## PR Summary

Prepare for release! 

@Yurlungur @jhp-lanl @rbberger @mauneyc-LANL 

## PR Checklist

- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Format your changes by using the `make format` command after configuring with `cmake`.
- [x] Document any new features, update documentation for changes made.
- [x] Make sure the copyright notice on any files you modified is up to date.
- [x] After creating a pull request, note it in the CHANGELOG.md file.
- [x] LANL employees: make sure tests pass both on the github CI and on the Darwin CI

If preparing for a new release, in addition please check the following:
- [x] Update the version in cmake.
- [x] Move the changes in the CHANGELOG.md file under a new header for the new release, and reset the categories.

### CODE REVIEW

**Comment by jhp-lanl** [comment]
Before the release, can we take a hard look at our `package.py` and make sure the dependencies make sense. Basically I want to make sure the correct things are pointing `@1.9.0` rather than `@main`.

For example:
```python
depends_on("catch2@3.0.1:", when="@main +tests")
```
should be
```python
depends_on("catch2@3.0.1:", when="@1.9.0: +tests")
```
I think, right?

I also put in the `ports-of-call` 1.6.0 dependency, but I chose a non-existent version number:
```python
depends_on("ports-of-call@1.6.0:", when="@1.8.1:")
```

I think those are the only two things that might need looking at.

**Comment by jhp-lanl** [comment]
> Before the release, can we take a hard look at our `package.py` and make sure the dependencies make sense. Basically I want to make sure the correct things are pointing `@1.9.0` rather than `@main`.

I should add, this can be done separate from this MR if need be

**Review by Yurlungur — APPROVED** [review]
Other than @jhp-lanl 's concerns LGTM

**Comment by jhp-lanl** [comment]
@rbberger can you take a look at the `package.py` and make sure my comments are correct and/or whether we need any other changes before release.

**Comment by jhp-lanl** [comment]
Other than updating the changelog, this looks good to me!

**Comment by dholladay00** [comment]
This is ready @Yurlungur @jhp-lanl

**Pull request merged**
