### PR TITLE
Fix for EOSPAC export/install scripts

### PR DESCRIPTION
**Pull request by mauneyc-LANL**
## PR Summary

This is a replacement for #230 .

The export/install stage will generate the file `singularity-eosConfig.cmake`, which is used by the `find_package()` command downstream. This file checks for the required dependencies, defines targets and some variables.

```cmake
# example of prior singularity-eosConfig.cmake, notice that EOSPAC is missing from the pattern. This is a bug.
if(NOT spiner_FOUND OR NOT TARGET spiner::spiner)
        find_package(spiner  REQUIRED)
endif()
if(NOT HDF5_FOUND OR NOT TARGET hdf5::hdf5 OR NOT TARGET hdf5::hdf5_hl)
        find_package(HDF5 COMPONENTS C;HL REQUIRED)
endif()
if(NOT MPI_FOUND OR NOT TARGET MPI::MPI_CXX)
        find_package(MPI COMPONENTS CXX REQUIRED)
endif()
```

There was a typo in the variable used to add `EOSPAC` to the set of required packages, and a variable for checking on the correct target guard. With this fix, we have the correct propagation:

```cmake
# example of new singularity-eosConfig.cmake
if(NOT spiner_FOUND OR NOT TARGET spiner::spiner)
        find_package(spiner  REQUIRED)
endif()
if(NOT HDF5_FOUND OR NOT TARGET hdf5::hdf5 OR NOT TARGET hdf5::hdf5_hl)
        find_package(HDF5 COMPONENTS C;HL REQUIRED)
endif()
if(NOT MPI_FOUND OR NOT TARGET MPI::MPI_CXX)
        find_package(MPI COMPONENTS CXX REQUIRED)
endif()
if(NOT EOSPAC_FOUND OR NOT TARGET EOSPAC::eospac)
        find_package(EOSPAC  REQUIRED)
endif()
```

This only effects downstream codes that rely on `find_package()` for resolving `singularity-eos`; in-tree builds, or otherwise "install-less" use-cases, would be unaffected.

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.
- [ ] Make sure the copyright notice on any files you modified is up to date.
- [ ] After creating a pull request, note it in the CHANGELOG.md file
- [ ] If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Comment by dholladay00** [comment]
@mauneyc-LANL when are the circumstances in which eospac would be a target like that already? 

Would this need to change again with your other larger cmake changes? Is this a change that could be part of that PR or is it better to separate? If not, we could make the target branch your cmake changes branch.

**Comment by mauneyc-LANL** [comment]
> @mauneyc-LANL when are the circumstances in which eospac would be a target like that already?
> 
> Would this need to change again with your other larger cmake changes? Is this a change that could be part of that PR or is it better to separate? If not, we could make the target branch your cmake changes branch.

If it was defined beforehand. `find_package(EOSPAC)`, `find_package(singularity-eos)`.

This is simple change, merging it now is easiest path.

**Comment by mauneyc-LANL** [comment]
> This is just a 1-line change? Assuming this resolves build issues, LGTM.
> 
> Longer-term it seems like our "install" tests aren't catching this stuff. Is there another CI test we could add that catches the use-case we're hitting?

Yes; we could update the examples to be "isolated" from the build and do a `find_package` (this is how I'm testing locally)

**Comment by mauneyc-LANL** [comment]
> This is just a 1-line change? Assuming this resolves build issues, LGTM.
> 

This resolves a hypothetical build issue, e.g. someone does `find_package(singularity-eos)` but hasn't defined the `EOSPAC` target. In all extant use-cases, this isn't strictly necessary as this is already present in the build. But this is to cover any case where it would possibly not be (that is, the installed `singularity-eos` was built with `EOSPAC`, but for whatever reason some host code doesn't do `find_package(EOSPAC)` or similar before doing `find_package(singularity-eos)`).

**Comment by Yurlungur** [comment]
> > This is just a 1-line change? Assuming this resolves build issues, LGTM.
> > Longer-term it seems like our "install" tests aren't catching this stuff. Is there another CI test we could add that catches the use-case we're hitting?
> 
> Yes; we could update the examples to be "isolated" from the build and do a `find_package` (this is how I'm testing locally)

This is probably a good idea. So long as we can also let users build examples easily still. For another day though.

**Pull request merged**
