### PR TITLE
spack: add spiner v1.6.0 and ports-of-call v1.3.0

### PR DESCRIPTION
**Pull request by rbberger**
## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.
- [ ] Make sure the copyright notice on any files you modified is up to date.
- [ ] After creating a pull request, note it in the CHANGELOG.md file
- [ ] If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
LGTM. Happy to merge if @ktsai7 and @mauneyc-LANL are happy and it doesn't break the CI on re-git. Please add to the changelog before merge. :)

**Comment by rbberger** [comment]
@Yurlungur there is still something going on with the re-git CI, which I'm trying fix.

**Comment by Yurlungur** [comment]
@rbberger ok. I'll let you merge when you're ready then. Approved on my end unless it is significantly different.

**Review by ktsai7 — APPROVED** [review]

**Comment by ktsai7** [comment]
@rbberger I didn’t say anything since I thought if just moving it to a separate folder fix the issues, that’s fine by me. But if you are having problems, you could always try to just source that loads file instead of module loading it

**Comment by rbberger** [comment]
@ktsai7 Thanks for the suggestion. Yes, moving seems to fix it too, since Lmod doesn't like non-modules in a given folder. But probably the sourcing will be a smaller change. I'll test that once I figured out the other issues (Python dependencies, etc).

**Pull request merged**
