### PR TITLE
Spack updates

### PR DESCRIPTION
**Pull request by mauneyc-LANL**
Changes:

- `mpi` variant propagated to dependencies correctly
- re-implementation of cmake configuration file generation.
- documentation stubs

Fixing various issues with spack installations that have arisen. Will try and address open issues here.

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.

### CODE REVIEW

**Comment by ktsai7** [comment]
Does `singularity-eos` have to be on `eigen@3.3.9`, `catch2@2.13.4:2.13.6` and `kokkos@develop`?

Would `eigen@3.3.8`, `catch2@2.12.3`, `kokkos@3.2.00` be acceptable as well?

**Comment by Yurlungur** [comment]
> Does `singularity-eos` have to be on `eigen@3.3.9`, `catch2@2.13.4:2.13.6` and `kokkos@develop`?
> 
> Would `eigen@3.3.8`, `catch2@2.12.3`, `kokkos@3.2.00` be acceptable as well?

From my perspective those would all be fine.

**Review by Yurlungur — COMMENTED** [review]
Thanks for doing this, and adding the cmake config file back in. That's great to have.

**Comment by ktsai7** [comment]
> > Does `singularity-eos` have to be on `eigen@3.3.9`, `catch2@2.13.4:2.13.6` and `kokkos@develop`?
> > Would `eigen@3.3.8`, `catch2@2.12.3`, `kokkos@3.2.00` be acceptable as well?
> 
> From my perspective those would all be fine.

Then it would be nice if we don't required the package version that only start existing on/after spack@v0.17 or spack@develop

**Comment by cmauney** [comment]
> Does `singularity-eos` have to be on `eigen@3.3.9`, `catch2@2.13.4:2.13.6` and `kokkos@develop`?
> 
> Would `eigen@3.3.8`, `catch2@2.12.3`, `kokkos@3.2.00` be acceptable as well?

These have been set in cbdae9f

**Comment by cmauney** [comment]
Spec with GPU support (gcc@9.4.0):

`singularity-eos+cuda+kokkos+kokkos-kernels build_extra=sesame,stellarcollapse cuda_arch=70`

**Comment by cmauney** [comment]
@ktsai7 @Yurlungur @dholladay00 

The workflow has changed somewhat. If you want to just install dependencies, *but not the pre-configured cmake*, you can simply do
```
$> spack install --only dependencies singularity-eos
```
If you *do* want the pre-configured cmake, you have do a regular install
```
$> spack install singularity-eos
```
This will do a full build of the repo and install it into spack's storage. The reason for this is, in order to cleanly install the preconfigured cmake cache, the spackage has to enter the install phase.

I've tried a few hacks to get around this using only internal spack logic, but so far nothing really sticks. One option to overcome this is to use a new variant, such as `+dev_only` or similar, and to short-circuit the spackage install routine to only install the cache file if it is set. I don't *love* this idea, but a custom install routine is not uncommon. Or, we could resurrect the `deps` spackage as an optional dependency, but it would only exist to generate the cmake cache.

Another option is to not bother, and just do a full build+install, as this provides a quick check that the compiler/arch/spec is compatible. This shouldn't interfere with a manual build (tho I don't know if I can guarantee this yet).

I will bang my head against this a little more, but if there are preferences and/or advice on how proceed let me know.

**Comment by Yurlungur** [comment]
> I've tried a few hacks to get around this using only internal spack logic, but so far nothing really sticks. One option to overcome this is to use a new variant, such as `+dev_only` or similar, and to short-circuit the spackage install routine to only install the cache file if it is set. I don't _love_ this idea, but a custom install routine is not uncommon. Or, we could resurrect the `deps` spackage as an optional dependency, but it would only exist to generate the cmake cache.
> 
> Another option is to not bother, and just do a full build+install, as this provides a quick check that the compiler/arch/spec is compatible. This shouldn't interfere with a manual build (tho I don't know if I can guarantee this yet).

I don't have a strong preference between these options... if we were to submit this upstream to the public spack repos, is there a preferred solution that the spack team would encourage?

**Comment by cmauney** [comment]
> > I've tried a few hacks to get around this using only internal spack logic, but so far nothing really sticks. One option to overcome this is to use a new variant, such as `+dev_only` or similar, and to short-circuit the spackage install routine to only install the cache file if it is set. I don't _love_ this idea, but a custom install routine is not uncommon. Or, we could resurrect the `deps` spackage as an optional dependency, but it would only exist to generate the cmake cache.
> > Another option is to not bother, and just do a full build+install, as this provides a quick check that the compiler/arch/spec is compatible. This shouldn't interfere with a manual build (tho I don't know if I can guarantee this yet).
> 
> I don't have a strong preference between these options... if we were to submit this upstream to the public spack repos, is there a preferred solution that the spack team would encourage?

I'm under the impression is they would rather this sort of thing happen outside of spack, which is also an option (e.g. some script)

**Comment by dholladay00** [comment]
I like the script idea, especially if this is a tool that only devs are going to need and the host codes are just going to use spack in the intended way.

**Comment by Yurlungur** [comment]
How would the script machinery work? Installing via spack would provide a script in the binary directory or something?

**Comment by dholladay00** [comment]
hmmm... this is a good question. I guess I was simplistically thinking the script could live in `/utils/scripts`, but I'm not sure how it would know anything about the spack installation.

**Review by Yurlungur — APPROVED** [review]
Although I think there's still interest in getting the cmake config independent of the build... I think we should get these changes in regardless, and tackle that question later. Any objections to merging this in?

**Comment by dholladay00** [comment]
lets go ahead and merge

**Pull request merged**
