### PR TITLE
revert spiner release in spackage

### PR DESCRIPTION
**Pull request by Yurlungur**
## PR Summary

The bots did their job with the spiner spackage, but because singularity-eos wasn't pinned to a specific spiner release in its own spackage, this broke the CI since spiner is a bit ahead of singularity-eos, at least until @mauneyc-LANL 's PR #246 goes through. This pins singularity to a version of spiner that it works with.

@mauneyc-LANL when you merge PR #246 please make sure to update the spackage here.

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.
- [ ] Make sure the copyright notice on any files you modified is up to date.
- [x] After creating a pull request, note it in the CHANGELOG.md file
- [ ] If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Review by jhp-lanl — APPROVED** [review]
I think maybe we can remote the "This should be removed" comment since pinning to a specific version isn't a bad thing. We just need to be conscious about updating the version, but I think it makes sense for that _not_ to be automated since we will want to test the new version properly.

**Comment by Yurlungur** [comment]
> I think maybe we can remote the "This should be removed" comment since pinning to a specific version isn't a bad thing. We just need to be conscious about updating the version, but I think it makes sense for that _not_ to be automated since we will want to test the new version properly.

Agreed. I modified it to say "set to pinned version." Or at least I tried. github doesn't seem to be registering the commit or the diff.

**Comment by Yurlungur** [comment]
Very strange. If I look at the branch, the commit is visible in the branch history and the file. But the PR doesn't show it. Don't know what to make of that. Just going to assume it's correct and the PR web API is doing something weird

**Comment by jhp-lanl** [comment]
> Very strange. If I look at the branch, the commit is visible in the branch history and the file. But the PR doesn't show it. Don't know what to make of that. Just going to assume it's correct and the PR web API is doing something weird

This is what you're seeing?

Screen Shot 2023-07-31 at 1 02 56 PM

**Comment by Yurlungur** [comment]
Yeah that's what I'm seeing, but if I inspect the branch manually, it's there:
https://github.com/lanl/singularity-eos/commits/jmm/spiner-hotfix

**Comment by jhp-lanl** [comment]
> Yeah that's what I'm seeing, but if I inspect the branch manually, it's there: https://github.com/lanl/singularity-eos/commits/jmm/spiner-hotfix

That's bizarre. Oh well. Thanks for the fix!

**Comment by mauneyc-LANL** [comment]
I had merged this into my branch (#246 ) , but I'm confused on how I should edit the spackage and want to clarify the workflow.

In my branch, I have 

```python
    depends_on("spiner@:1.6.0", when="@:1.7.0")
    depends_on("spiner@1.6.1:", when="@1.7.1:") #TODO version
    depends_on("spiner@main", when="@main")
```

That is, I've set it up such that when `singularity-eos` is less than v.1.7.0, I depend on `spiner` versions less than `spiner@1.6.0`, and depend higher versions when `singularity-eos` is spec'd with versions higher than the (as yet unreleased) version 1.7.1 (or whatever version number to attach to the update). I've added similar code for `ports-of-call`

Is this in conflict with the "bot"?

**Comment by Yurlungur** [comment]
No---you're fine. The problem was that the current main didn't pin to a spiner version. So the spack pulled the most recent release. This PR fixes that. If you pin to a version, we're good.

**Pull request merged**
