### PR TITLE
Enable fortran preprocessor for fortran interface and then add same l…

### PR DESCRIPTION
**Pull request by dholladay00**
…ogic in fortran interface as is in the c/c++ interface.

## PR Summary
Fortran interface build issues can abound when certain Eos's are disabled via preprocessor macros. This PR enables the preprocessor in the fortran interface and adds the same preprocessor logic that exists in the c/c++ interface files in the fortran interface files to resolve fortran build/link issues. 

## PR Checklist

- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Format your changes by using the `make format` command after configuring with `cmake`.
- [x] Document any new features, update documentation for changes made.
- [x] Make sure the copyright notice on any files you modified is up to date.
- [x] After creating a pull request, note it in the CHANGELOG.md file
- [x] If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
Make sure to add to the changelog. Other than that LGTM. Click the button when you're happy with it.

**Review by jhp-lanl — APPROVED** [review]
I had to make these changes in https://github.com/lanl/singularity-eos/pull/278, and making them a separate MR is probably a good idea.

I also forgot that the Helmholtz EOS requires spiner

**Comment by jhp-lanl** [comment]
@dholladay00 we can pull the trigger when you tell us this is ready

**Comment by jhp-lanl** [comment]
@dholladay00 is there anything holding this MR up or can we merge?

**Comment by dholladay00** [comment]
This is ready to merge @jhp-lanl

**Comment by jhp-lanl** [comment]
Thanks @dholladay00 !

**Pull request merged**
