### PR TITLE
Remove extraneous `SG_USING`. Resolves #112

### LINKED ISSUE #112: Build error from last pull
To reproduce

```bash
$> git checkout main; git pull
$> mkdir build; cd build
$> cmake ..
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 11.2.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped
-- Patching mpark::variant to support GPUs
Reversed (or previously applied) patch detected!  Skipping patch.
12 out of 12 hunks ignored -- saving rejects to file singularity-eos/utils/variant/include/mpark/variant.hpp.rej
-- Found HDF5: hdf5-shared (found version "1.12.1") found components: C HL 
-- Found Eigen3:   
-- Found PortsofCall:   
-- clang-format --version: 13.0.1
CMake Warning at cmake/Format.cmake:45 (message):
  clang-format version 12.0 is required - results on other versions may not
  be stable
Call Stack (most recent call first):
  CMakeLists.txt:384 (include)


-- Configuring done
-- Generating done

$> cmake --build .
```

Error:

```bash
[  8%] Building CXX object singularity-eos/eos/CMakeFiles/eos_objs.dir/eos_spiner.cpp.o
In file included from /home/mauneyc/devel/singularity_local/singularity-eos/singularity-eos/eos/eos.hpp:27,
                 from /home/mauneyc/devel/singularity_local/singularity-eos/singularity-eos/eos/eos_spiner.cpp:30:
/home/mauneyc/devel/singularity_local/singularity-eos/singularity-eos/eos/eos.hpp:859:3: error: redeclaration of ‘using singularity::eos_base::EosBase<singularity::StellarCollapse>::PTofRE’
  859 |   SG_ADD_BASE_CLASS_USINGS(StellarCollapse)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from singularity-eos/singularity-eos/eos/eos_spiner.cpp:30:
singularity-eos/singularity-eos/eos/eos.hpp:802:35: note: previous declaration ‘using singularity::eos_base::EosBase<singularity::StellarCollapse>::PTofRE’
  802 |   using EosBase<StellarCollapse>::PTofRE;
      |                                   ^~~~~~
make[2]: *** [singularity-eos/eos/CMakeFiles/eos_objs.dir/build.make:76: singularity-eos/eos/CMakeFiles/eos_objs.dir/eos_spiner.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:184: singularity-eos/eos/CMakeFiles/eos_objs.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### PR DESCRIPTION
**Pull request by Yurlungur**
## PR Summary

Introduced by me in #109. Reported by @mauneyc-LANL . Resovles #112 .

## PR Checklist

- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Format your changes by using the `make format` command after configuring with `cmake`.
- [x] Document any new features, update documentation for changes made.
- [x] Make sure the copyright notice on any files you modified is up to date.

### CODE REVIEW

**Comment by Yurlungur** [comment]
Since CI currently not working on Darwin, github tests + hand-verification will have to be enough.

**Comment by Yurlungur** [comment]
@mauneyc-LANL can you please try this and approve if it solves your issue?

**Comment by mauneyc-LANL** [comment]
This fixes #112 for me

**Review by mauneyc-LANL — APPROVED** [review]
Fixes build issue.

**Pull request merged**
