### PR TITLE
Add sphinx building instructions to documentation

### PR DESCRIPTION
**Pull request by jhp-lanl**
## PR Summary
Provides basic instructions for getting `sphinx` working with python. This is easy because most shared machines have python and you can just install sphinx and the RTD style via `pip`.

In my opinion, this is by far the easiest way to build the documentation.

Fixes https://github.com/lanl/singularity-eos/issues/204

## PR Checklist

- N/A Adds a test for any bugs fixed. Adds tests for new features.
- N/A Format your changes by using the `make format` command after configuring with `cmake`.
- [x] Document any new features, update documentation for changes made.
- N/A Make sure the copyright notice on any files you modified is up to date.
- [x] After creating a pull request, note it in the CHANGELOG.md file

### CODE REVIEW

**Comment by jhp-lanl** [comment]
@aematts this may help you

@ktsai7 any issues with this?

@Yurlungur @jonahm-LANL FYI

**Comment by jhp-lanl** [comment]
Whoops... forgot the essential commit at first lol

**Review by Yurlungur — APPROVED** [review]
I made a quick change as well moving the "automated build" to the top of the doc page and making it hopefully a little clearer.

**Comment by Yurlungur** [comment]
Thanks for adding this @jhp-lanl !

**Pull request merged**
