### PR TITLE
Spack package

### PR DESCRIPTION
**Pull request by mauneyc-LANL**
## PR Summary
This PR will replace the `singularity-eos-deps` spack package with a full `singularity-eos` spack package in `spack-repo`, allowing for both installing dependencies and the library.

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.

### CODE REVIEW

**Comment by mauneyc-LANL** [comment]
I anticipate a multi-stage processes here

1. merge this without disturbing the existing `-deps` `package.py`
2. another to update the CI to no longer use the `-deps`
3. another to remove the `deps`

**Comment by ktsai7** [comment]
The multi-stage process is probably the best way to try to avoid breaking the CI

**Comment by cmauney** [comment]
Is there anything blocking merging that needs to be addressed? @dholladay00 @ktsai7 @jonahm-LANL

**Review by dholladay00 — APPROVED** [review]

**Review by Yurlungur — APPROVED** [review]
Ah, my apologies. No I'm happy with this. Let me know if you want to merge.

**Comment by dholladay00** [comment]
this is merely a formality, but @mauneyc-LANL can you remove the draft status?

**Comment by mauneyc-LANL** [comment]
> this is merely a formality, but @mauneyc-LANL can you remove the draft status?

I didn't even notice it was still draft - changed

**Pull request merged**
