### PR TITLE
Fixed typo in documentation

### PR DESCRIPTION
**Pull request by gopsub**
## PR Checklist

- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Format your changes by using the `make format` command after configuring with `cmake`.
- [x] Document any new features, update documentation for changes made.
- [x] Make sure the copyright notice on any files you modified is up to date.
- [x] After creating a pull request, note it in the CHANGELOG.md file.
- [x] LANL employees: make sure tests pass both on the github CI and on the Darwin CI

If preparing for a new release, in addition please check the following:
- [ ] Update the version in cmake.
- [ ] Move the changes in the CHANGELOG.md file under a new header for the new release, and reset the categories.

### CODE REVIEW

**Review by jhp-lanl — APPROVED** [review]
Thanks for catching this @gopsub

**Comment by jhp-lanl** [comment]
Let us know when this is ready to be merged

**Comment by gopsub** [comment]
It's not particularly controversial, so, ready to merge now, I think. Any housekeeping items that need to be done?

**Comment by jhp-lanl** [comment]
> It's not particularly controversial, so, ready to merge now, I think. Any housekeeping items that need to be done?

I don't think there are any related to this EOS at least. Merging

**Pull request merged**
