### PR TITLE
Fix typo in documentation

### PR DESCRIPTION
**Pull request by jhp-lanl**
## PR Summary

Fixes a small typo in the closure model documentation

## PR Checklist

- N/A Adds a test for any bugs fixed. Adds tests for new features.
- N/A Format your changes by using the `make format` command after configuring with `cmake`.
- [x] Document any new features, update documentation for changes made.
- N/A Make sure the copyright notice on any files you modified is up to date.
- N/A After creating a pull request, note it in the CHANGELOG.md file.
- N/A LANL employees: make sure tests pass both on the github CI and on the Darwin CI

If preparing for a new release, in addition please check the following:
- N/A Update the version in cmake.
- N/A Move the changes in the CHANGELOG.md file under a new header for the new release, and reset the categories.

### CODE REVIEW

**Review by aematts — APPROVED** [review]
Looks right.

**Comment by jhp-lanl** [comment]
Thanks for the approval @aematts ! To my eye this looks good so I'll merge it in.

Screenshot 2024-02-22 at 6 33 43 PM

FYI @jonahm-LANL since I think you wrote this

**Comment by aematts** [comment]
Did you see my last Mattermost comment?


From: Jeff Peterson ***@***.***>
Reply-To: lanl/singularity-eos ***@***.***>
Date: Thursday, February 22, 2024 at 6:34 PM
To: lanl/singularity-eos ***@***.***>
Cc: Ann Wills ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [lanl/singularity-eos] Fix typo in documentation (PR #349)


Thanks for the approval @aematts<https://urldefense.com/v3/__https:/github.com/aematts__;!!Bt8fGhp8LhKGRg!GhStAHU0z3vuUMQJpctH-IHMA-7zNr37te6TIPjXAUaHRH2DJBg1NUXTXZTBoy7kOYVDBtg23T39BZ9KsbNmt6fd$> ! To my eye this looks good so I'll merge it in.

Screenshot.2024-02-22.at.6.33.43.PM.png (view on web)<https://urldefense.com/v3/__https:/github.com/lanl/singularity-eos/assets/83598606/bf9534e9-ac22-4ed7-90ac-0012fa26fb74__;!!Bt8fGhp8LhKGRg!GhStAHU0z3vuUMQJpctH-IHMA-7zNr37te6TIPjXAUaHRH2DJBg1NUXTXZTBoy7kOYVDBtg23T39BZ9KsRb7EoZ2$>

FYI @jonahm-LANL<https://urldefense.com/v3/__https:/github.com/jonahm-LANL__;!!Bt8fGhp8LhKGRg!GhStAHU0z3vuUMQJpctH-IHMA-7zNr37te6TIPjXAUaHRH2DJBg1NUXTXZTBoy7kOYVDBtg23T39BZ9KsadAjyhU$> since I think you wrote this

**Comment by Yurlungur** [comment]
Yeah I wrote this and this is fix is correct. Thanks for the fix!

**Comment by aematts** [comment]
I found one more place that needs to be updated: You have rho without bar in the The Density-Temperature Formulation section too.

**Pull request merged**
