### PR TITLE
move the singularity_eos cpp files back into the fortran build only

### PR DESCRIPTION
**Pull request by Yurlungur**
## PR Summary

As @dholladay00 commented in PR #348 , the `singularity_eos.{cpp,hpp}` files should only be built when fortran is on to minimize build times for C++ codes. This reverts that change. 

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.
- [ ] Make sure the copyright notice on any files you modified is up to date.
- [ ] After creating a pull request, note it in the CHANGELOG.md file.
- [ ] LANL employees: make sure tests pass both on the github CI and on the Darwin CI

If preparing for a new release, in addition please check the following:
- [ ] Update the version in cmake.
- [ ] Move the changes in the CHANGELOG.md file under a new header for the new release, and reset the categories.

### CODE REVIEW

**Review by dholladay00 — APPROVED** [review]

**Comment by Yurlungur** [comment]
@rbberger please confirm this is ok. then will merge.

**Comment by rbberger** [comment]
@Yurlungur do you have a re-git pipeline to show this works?

**Comment by rbberger** [comment]
If there are no C++ source files in the singularity-eos_Library, we need to change it to an INTERFACE library in that case.

**Comment by Yurlungur** [comment]
> @Yurlungur do you have a re-git pipeline to show this works?

No re-git was down

> If there are no C++ source files in the singularity-eos_Library, we need to change it to an INTERFACE library in that case.

This was why I had that dummy C++ file in there... should we revive that?

**Comment by rbberger** [comment]
I think we can do it in a way which just avoids defining the _Library in the `NOT (CLOSURE && FORTRAN)` case. I'll need to look into that.

**Comment by Yurlungur** [comment]
Sounds good. I'll hold off on merging this then. Do you just want to push to this branch?

**Comment by rbberger** [comment]
Will do.

**Comment by rbberger** [comment]
Pushed a change, need to wait until the CI gives us some feedback.

**Comment by Yurlungur** [comment]
> Pushed a change, need to wait until the CI gives us some feedback.

When re-git comes back online do you want to push there? Or should I?

**Comment by rbberger** [comment]
@Yurlungur there is a problem with this PR, since there are clients of the .cpp files other than Fortran. They are used in the unit tests.

**Comment by Yurlungur** [comment]
> @Yurlungur there is a problem with this PR, since there are clients of the .cpp files other than Fortran. They are used in the unit tests.

Ah good point. What if we hide those added files/this cmake logic behind fortran *or* testing?

**Review by rbberger — APPROVED** [review]
This is ready from my point of view.

**Pull request merged**
