### PR TITLE
Jmm/compare to eospac no ses2spiner

### PR DESCRIPTION
**Pull request by Yurlungur**
## PR Checklist

Quick bug fix for `compare_to_eospac.cpp`. Also cleans it up by not using `io_eospac.hpp` to provide the `Bounds` class.

- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [x] Format your changes by using the `make format` command after configuring with `cmake`.
- [x] Document any new features, update documentation for changes made.
- [x] Make sure the copyright notice on any files you modified is up to date.

### CODE REVIEW

**Comment by Yurlungur** [comment]
Depends on #105. Do not merge until that's in.

**Comment by Yurlungur** [comment]
I don't think anyone cares about this PR but me. Merging by fiat.

**Comment by dholladay00** [comment]
is the bounds class now defined in 2 places?

**Comment by Yurlungur** [comment]
Yes, and the implementations are slightly different. The `sesame2spiner` one should get namespaced. For now however it's not an issue as `compare_to_eospac` no longer uses `sesame2spiner`.

**Comment by dholladay00** [comment]
could we put the implementation in a header included in both places to prevent code duplication?

**Comment by Yurlungur** [comment]
Yes technically, but it would require me abstracting out some functionality. The issue is the one in `sesame2spiner` uses the new fast logs, whereas the one in `compare_to_eospac` uses `std::log10`. I don't think it's worth worrying about.

**Pull request merged**
