### PR TITLE
Draft: mess with cmake until submodule build works downstream

### PR DESCRIPTION
**Pull request by jdolence**
## PR Summary

Tried to use singularity-eos in a downstream code as a submodule and the cmake seems broken.  Here, I just hacked at it until I got it to work.  Haven't tested basically anything, but I am at least building successfully now.

I'm not the right person to fix this properly, but I wanted to bring it to somebody's attention.  @mauneyc-LANL @jonahm-LANL @Yurlungur 

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.
- [ ] Make sure the copyright notice on any files you modified is up to date.
- [ ] After creating a pull request, note it in the CHANGELOG.md file
- [ ] If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Comment by mauneyc-LANL** [comment]
I think that `CMAKE_MODULE_PATH` is maybe getting confused with submodules.

A more comprehensive, simpler fix maybe just changing

```cmake
# CMakeLists.txt:30
list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")
```

to

```cmake
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")
```

Or, maybe more verbosely, updating the module path as above but under checks for submodule mode.

**Comment by Yurlungur** [comment]
@jdolence does @mauneyc-LANL 's suggested change fix your issue? I notice that the current version broke tests for the standalone build in the CI.

**Comment by mauneyc-LANL** [comment]
@rbberger

**Comment by Yurlungur** [comment]
Fixed by @mauneyc-LANL in #296

**Pull request closed without merging**
