### PR TITLE
Fix pressure from density temperature function in shift modifier.

### PR DESCRIPTION
**Pull request by dholladay00**
## PR Summary
Bug fix. Discussed with Jonah. 

## PR Checklist

- [x] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by using the `make format` command after configuring with `cmake`.
- [x] Document any new features, update documentation for changes made.
- [ ] Make sure the copyright notice on any files you modified is up to date.

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
Thanks for the catch!

**Comment by jhp-lanl** [comment]
Can we add a test for this? Maybe just make sure that a shift of 0 returns the same result as the EOS?

**Comment by Yurlungur** [comment]
@dholladay00 looks like formatting is failing.

**Review by jhp-lanl — APPROVED** [review]

**Comment by jhp-lanl** [comment]
@dholladay00 @jonahm-LANL has a tool in the `utils` folder to auto format. Just run
```
bash utils/scripts/format.sh
```
from the top of the repo.

Maybe the cmake way works as well, but I find this easiest.

**Pull request merged**
