### PR TITLE
Update ports-of-call to latest master

### PR DESCRIPTION
**Pull request by jhp-lanl**
## PR Summary

Pretty straight-forward. Just update `ports-of-call` to the latest master.

This is needed to make full use of the portable errors.

## PR Checklist

- N/A Adds a test for any bugs fixed. Adds tests for new features.
- N/A Format your changes by using the `make format` command after configuring with `cmake`.
- N/A Document any new features, update documentation for changes made.
- N/A Make sure the copyright notice on any files you modified is up to date.
- [x] After creating a pull request, note it in the CHANGELOG.md file
- N/A If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Comment by jhp-lanl** [comment]
@Yurlungur this just updates `ports-of-call` to avoid the undefined behavior we just fixed. This is necessary for
https://github.com/lanl/singularity-eos/pull/233

**Review by Yurlungur — APPROVED** [review]

**Review by rbberger — APPROVED** [review]
We also need this in spiner

**Comment by Yurlungur** [comment]
Yes good point. I'll add it.

**Comment by Yurlungur** [comment]
https://github.com/lanl/spiner/pull/61

**Comment by jhp-lanl** [comment]
@Yurlungur this looks good to go. I haven't merged yet in case you have any last minute additions

**Pull request merged**
