### PR TITLE
ci: update

### PR DESCRIPTION
**Pull request by rbberger**
## PR Summary

- add ATS2 jobs
- update ATS4 to use `%cce`
- enable CDash reporting to internal LANL CDash server
- fixed a naming issue in the closure tests

Note: currently several CI jobs fail due to previous breakage.

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.
- [ ] Make sure the copyright notice on any files you modified is up to date.
- [ ] After creating a pull request, note it in the CHANGELOG.md file.
- [ ] LANL employees: make sure tests pass both on the github CI and on the Darwin CI

If preparing for a new release, in addition please check the following:
- [ ] Update the version in cmake.
- [ ] Move the changes in the CHANGELOG.md file under a new header for the new release, and reset the categories.
- [ ] Ensure that any `when='@main'` dependencies are updated to the release version in the package.py

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
LGTM. Merge when ready @rbberger

**Comment by rbberger** [comment]
Waiting to see if @jhp-lanl can fix some of the remaining failures.

**Comment by jhp-lanl** [comment]
Sorry I didn't get to this yesterday. I'll look right now

**Comment by jhp-lanl** [comment]
I'm running into what I think is a proxy error. It may take me a while to debug

**Comment by jhp-lanl** [comment]
I _think_ I found the error, but I'm unable to build (and I think I can't run the CI either on LANL machines).

I'd just merge this and I can try to tackle the CI issues when my proxy issues are resolved.

**Comment by jhp-lanl** [comment]
I was able to reproduce and fix the error on rocinante. I'm running the gitlab CI now. @rbberger one of us can merge when the gitlab CI passes

**Pull request merged**
