### PR TITLE
Added untracked headers in cmake

### PR DESCRIPTION
**Pull request by cmauney**
## PR Summary

Addressing #227 . `singularity-eos/CMakeLists.txt` updated to include all header files in code.

This could be an impetus to automate source file discovery in the build, but my impression is `GLOB` and similar commands are not recommended. This could be an outdated mode of thought, tho.

## PR Checklist

- N/A  Adds a test for any bugs fixed. Adds tests for new features.
- N/A  Format your changes by using the `make format` command after configuring with `cmake`.
- [x] Document any new features, update documentation for changes made.
- [x] Make sure the copyright notice on any files you modified is up to date.
- [x] After creating a pull request, note it in the CHANGELOG.md file
- N/A If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Comment by mauneyc-LANL** [comment]
@dholladay00

**Comment by dholladay00** [comment]
Have you tested to make sure we're not missing anything else?

**Comment by mauneyc-LANL** [comment]
> Have you tested to make sure we're not missing anything else?

Just `find` on command line

**Comment by dholladay00** [comment]
Would it be possible to add building against an installed singularity-eos in the CI @mauneyc-LANL ?

**Comment by mauneyc-LANL** [comment]
> Would it be possible to add building against an installed singularity-eos in the CI @mauneyc-LANL ?

There's already an install test run on github CI. It just checks for one header, so that's likely why it wasn't caught.

**Review by Yurlungur — APPROVED** [review]

**Comment by Yurlungur** [comment]
Thanks for the quick fix @mauneyc-LANL . I suppose we could add an install test that checks for more headers but I'm not sure what the size of that list ends up.

**Pull request merged**
